name: Basekernel Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      run: sudo apt-get install -y genisoimage

    - name: Set PATH
      run: export PATH="$PWD/cross/bin:$PATH"
      
    - name: Build Kernel
      run: make build-kernel

    - name: Build Standard Library
      run: make build-library

    - name: Build Userspace
      run: make build-userspace

    - name: Build CDROM Image
      run: make build-cdrom-image

     
